# Generated by Django 4.2.11 on 2024-10-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=10)),
            ],
        ),
    ]
