# Generated by Django 4.2.11 on 2024-10-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_category_instructor_student_remove_course_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=' Description', max_length=400),
        ),
    ]
