# Generated by Django 4.2.11 on 2024-10-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_category_course_instructor_student_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imageCourse',
            field=models.ImageField(blank=True, null=True, upload_to='photos/cource'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='imageInstructor',
            field=models.ImageField(blank=True, null=True, upload_to='photos/Instructor'),
        ),
    ]
