# Generated by Django 4.2.11 on 2024-10-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_course_imagecourse_instructor_imageinstructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='imageCourse',
            field=models.ImageField(blank=True, null=True, upload_to='photos/course'),
        ),
    ]
