# Generated by Django 4.2.11 on 2024-10-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_alter_course_imagecourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='imageCourse',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
